apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-169983629
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-169983629
    app.kubernetes.io/part-of: test-app-169983629
  name: python-basic-169983629cw8w
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: python-basic-169983629
    weight: null
status: {}
