apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-169983629
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-169983629
    app.kubernetes.io/part-of: test-app-169983629
  name: python-basic-169983629
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-basic-169983629
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-basic-169983629
    spec:
      containers:
      - image: quay.io/hacdev/fbxzowfx-tenant/test-app-169983629/python-basic-169983629@sha256:9602381d21ae7ca50ccf5337ef78fb321a8bdadf3c07536185aa85c094d66602
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
